namespace PragimCourses.Migrations
{
    using System.Data.Entity.Migrations;

    public partial class SeedingData : DbMigration
    {
        public override void Up()
        {
            Sql(@"
                SET IDENTITY_INSERT [dbo].[Categories] ON
                INSERT INTO [dbo].[Categories] ([Id], [Name]) VALUES (3, N'ClassRoom Courses')
                INSERT INTO [dbo].[Categories] ([Id], [Name]) VALUES (2, N'Download Courses')
                INSERT INTO [dbo].[Categories] ([Id], [Name]) VALUES (1, N'Free Courses')
                SET IDENTITY_INSERT [dbo].[Categories] OFF
            ");

            Sql(@"
                    SET IDENTITY_INSERT [dbo].[Courses] ON
                    INSERT INTO [dbo].[Courses] ([Id], [Header], [Description], [Price], [ImagePath]) VALUES (1, N'ASP.NET MVC', N'ASP.NET Core MVC Tutorial for Beginners | .NET Core Tutorial', CAST(15.00 AS Decimal(18, 2)), N'~/Content/Images/FreeCourses/asp-mvc-360x270.jpg')
                    INSERT INTO [dbo].[Courses] ([Id], [Header], [Description], [Price], [ImagePath]) VALUES (2, N'ASP.NET Razor Pages', N'ASP.NET Core Razor Pages Tutorial for Beginners', CAST(15.00 AS Decimal(18, 2)), N'~/Content/Images/FreeCourses/asp.net-core-razor-pages-tutorial-3-360x270.png')
                    INSERT INTO [dbo].[Courses] ([Id], [Header], [Description], [Price], [ImagePath]) VALUES (3, N'Angular Crud', N'Angular CRUD Tutorial', CAST(15.00 AS Decimal(18, 2)), N'~/Content/Images/FreeCourses/angularjsCURD-360x270.jpg')
                    INSERT INTO [dbo].[Courses] ([Id], [Header], [Description], [Price], [ImagePath]) VALUES (4, N'Bootstrap', N'Bootstrap Tutorial for Beginners', CAST(15.00 AS Decimal(18, 2)), N'~/Content/Images/FreeCourses/bootstrap.jpg')
                    INSERT INTO [dbo].[Courses] ([Id], [Header], [Description], [Price], [ImagePath]) VALUES (5, N'Javascript', N'JavaScript Tutorial for Beginners', CAST(15.00 AS Decimal(18, 2)), N'~/Content/Images/FreeCourses/java-script.jpg')
                    INSERT INTO [dbo].[Courses] ([Id], [Header], [Description], [Price], [ImagePath]) VALUES (6, N'JQuery', N'jQuery Tutorial for Beginners', CAST(15.00 AS Decimal(18, 2)), N'~/Content/Images/FreeCourses/jquery.jpg')
                    INSERT INTO [dbo].[Courses] ([Id], [Header], [Description], [Price], [ImagePath]) VALUES (7, N'Angular JS', N'AngularJS Tutorial for Beginners', CAST(15.00 AS Decimal(18, 2)), N'~/Content/Images/FreeCourses/angularjs.jpg')
                    INSERT INTO [dbo].[Courses] ([Id], [Header], [Description], [Price], [ImagePath]) VALUES (8, N'Angular 2', N'Angular 2 tutorial for beginners', CAST(15.00 AS Decimal(18, 2)), N'~/Content/Images/FreeCourses/angular2-360x270.jpg')
                    INSERT INTO [dbo].[Courses] ([Id], [Header], [Description], [Price], [ImagePath]) VALUES (9, N'Angular CLI', N'Angular CLI tutorial for beginners', CAST(15.00 AS Decimal(18, 2)), N'~/Content/Images/FreeCourses/angularjsCLI-360x270.jpg')
                    INSERT INTO [dbo].[Courses] ([Id], [Header], [Description], [Price], [ImagePath]) VALUES (10, N'Angular 6', N'Angular 6 tutorial for beginners', CAST(15.00 AS Decimal(18, 2)), N'~/Content/Images/FreeCourses/angularjs6-360x270.jpg')
                    INSERT INTO [dbo].[Courses] ([Id], [Header], [Description], [Price], [ImagePath]) VALUES (11, N'Web Services', N'ASP.NET Web Services Tutorial', CAST(15.00 AS Decimal(18, 2)), N'~/Content/Images/FreeCourses/webs-services.jpg')
                    INSERT INTO [dbo].[Courses] ([Id], [Header], [Description], [Price], [ImagePath]) VALUES (12, N'Web API', N'ASP.NET Web API Tutorial for Beginners', CAST(15.00 AS Decimal(18, 2)), N'~/Content/Images/FreeCourses/ASP.NET-Web-api.jpg')
                    INSERT INTO [dbo].[Courses] ([Id], [Header], [Description], [Price], [ImagePath]) VALUES (13, N'ASP.NET GridView', N'ASP.NET GridView Tutorial for Beginners', CAST(15.00 AS Decimal(18, 2)), N'~/Content/Images/FreeCourses/ASP.NET-GridView.jpg')
                    INSERT INTO [dbo].[Courses] ([Id], [Header], [Description], [Price], [ImagePath]) VALUES (14, N'Design patterns', N'Design patterns tutorial for Beginners', CAST(15.00 AS Decimal(18, 2)), N'~/Content/Images/FreeCourses/design-patterns.jpg')
                    INSERT INTO [dbo].[Courses] ([Id], [Header], [Description], [Price], [ImagePath]) VALUES (15, N'SQL Server', N'SQL Server Tutorial for Beginners | SQL Tutorial for Beginners', CAST(15.00 AS Decimal(18, 2)), N'~/Content/Images/FreeCourses/sql-1.jpg')
                    INSERT INTO [dbo].[Courses] ([Id], [Header], [Description], [Price], [ImagePath]) VALUES (16, N'SQL Q&A', N'SQL Server Interview Q&A', CAST(15.00 AS Decimal(18, 2)), N'~/Content/Images/FreeCourses/sqlqa-360x270.jpg')
                    INSERT INTO [dbo].[Courses] ([Id], [Header], [Description], [Price], [ImagePath]) VALUES (17, N'C# Interview', N'C# interview questions and answers', CAST(15.00 AS Decimal(18, 2)), N'~/Content/Images/FreeCourses/C-interview-questions-and-answers.jpg')
                    INSERT INTO [dbo].[Courses] ([Id], [Header], [Description], [Price], [ImagePath]) VALUES (18, N'Entity Framework', N'Entity Framework Tutorial', CAST(15.00 AS Decimal(18, 2)), N'~/Content/Images/FreeCourses/Entity-framework.jpg')
                    INSERT INTO [dbo].[Courses] ([Id], [Header], [Description], [Price], [ImagePath]) VALUES (19, N'Linq', N'LINQ Tutorial', CAST(15.00 AS Decimal(18, 2)), N'~/Content/Images/FreeCourses/linq-1-360x270.jpg')
                    INSERT INTO [dbo].[Courses] ([Id], [Header], [Description], [Price], [ImagePath]) VALUES (20, N'C Sharp', N'C Sharp tutorial for beginners', CAST(15.00 AS Decimal(18, 2)), N'~/Content/Images/FreeCourses/c.jpg')
                    INSERT INTO [dbo].[Courses] ([Id], [Header], [Description], [Price], [ImagePath]) VALUES (21, N'ADO.NET', N'ADO.NET tutorial for beginners', CAST(15.00 AS Decimal(18, 2)), N'~/Content/Images/FreeCourses/ado-net-360x270.jpg')
                    INSERT INTO [dbo].[Courses] ([Id], [Header], [Description], [Price], [ImagePath]) VALUES (22, N'ASP.NET', N'ASP.NET Tutorial for Beginners', CAST(15.00 AS Decimal(18, 2)), N'~/Content/Images/FreeCourses/asp.net_.jpg')
                    INSERT INTO [dbo].[Courses] ([Id], [Header], [Description], [Price], [ImagePath]) VALUES (23, N'All Courses', N'Download all Videos & Slides', CAST(170.00 AS Decimal(18, 2)), N'~/Content/Images/DownloadCourses/downloads-1-360x270.jpg')
                    INSERT INTO [dbo].[Courses] ([Id], [Header], [Description], [Price], [ImagePath]) VALUES (24, N'Videos & Slides', N'Buy DVD with all videos & slides', CAST(200.00 AS Decimal(18, 2)), N'~/Content/Images/DownloadCourses/slides-360x270.jpg')
                    INSERT INTO [dbo].[Courses] ([Id], [Header], [Description], [Price], [ImagePath]) VALUES (25, N'Slides', N'Download all slides', CAST(50.00 AS Decimal(18, 2)), N'~/Content/Images/DownloadCourses/downloads-1-360x270.jpg')
                    INSERT INTO [dbo].[Courses] ([Id], [Header], [Description], [Price], [ImagePath]) VALUES (26, N'ASP.NET Core', N'ASP.NET Core Tutorial for Beginners', CAST(50.00 AS Decimal(18, 2)), N'~/Content/Images/DownloadCourses/aspnet-360x270.png')
                    INSERT INTO [dbo].[Courses] ([Id], [Header], [Description], [Price], [ImagePath]) VALUES (27, N'Unit Testing', N'Unit Testing Videos, Slides & Code Files', CAST(10.00 AS Decimal(18, 2)), N'~/Content/Images/DownloadCourses/slides-360x270.jpg')
                    INSERT INTO [dbo].[Courses] ([Id], [Header], [Description], [Price], [ImagePath]) VALUES (28, N'Angular JS', N'Angular 1 (53 Videos & Slides - 7 Hours 10 Minutes)', CAST(50.00 AS Decimal(18, 2)), N'~/Content/Images/DownloadCourses/angularjs-360x270.jpg')
                    INSERT INTO [dbo].[Courses] ([Id], [Header], [Description], [Price], [ImagePath]) VALUES (29, N'Angular 2', N'Angular 2 (43 Videos & Slides - 7 Hours 27 Minutes)', CAST(50.00 AS Decimal(18, 2)), N'~/Content/Images/DownloadCourses/angularjs2-360x270.jpg')
                    INSERT INTO [dbo].[Courses] ([Id], [Header], [Description], [Price], [ImagePath]) VALUES (30, N'Angular CLI', N'Angular CLI (26 Videos & Slides - 3 Hours 30 Minutes)', CAST(25.00 AS Decimal(18, 2)), N'~/Content/Images/DownloadCourses/angular-cli-360x270.jpg')
                    INSERT INTO [dbo].[Courses] ([Id], [Header], [Description], [Price], [ImagePath]) VALUES (31, N'Angular CRUD', N'Angular CRUD (71 Videos & Slides - 11 Hours 36 Minutes)', CAST(50.00 AS Decimal(18, 2)), N'~/Content/Images/DownloadCourses/angularjs2-360x270.jpg')
                    INSERT INTO [dbo].[Courses] ([Id], [Header], [Description], [Price], [ImagePath]) VALUES (32, N'Angular 6', N'Angular 6 (38 Videos & Slides - 5 Hours 44 Minutes)', CAST(50.00 AS Decimal(18, 2)), N'~/Content/Images/DownloadCourses/download-360x270.jpeg')
                    INSERT INTO [dbo].[Courses] ([Id], [Header], [Description], [Price], [ImagePath]) VALUES (33, N'SOILD Design', N'SOLID Design Principles (6 Videos & Slides - 51 Minutes)', CAST(25.00 AS Decimal(18, 2)), N'~/Content/Images/DownloadCourses/DesignPatternsCSharp-360x270.png')
                    INSERT INTO [dbo].[Courses] ([Id], [Header], [Description], [Price], [ImagePath]) VALUES (34, N'Design Pattern', N'Design Patterns(20 Videos & Slides - 4 Hours)', CAST(50.00 AS Decimal(18, 2)), N'~/Content/Images/DownloadCourses/solid-principles-object-oriented-design-360x270.png')
                    INSERT INTO [dbo].[Courses] ([Id], [Header], [Description], [Price], [ImagePath]) VALUES (35, N'ASP.NET Web API', N'ASP.NET Web API Videos & Slides (39 Videos & Slides - 6 Hours 55 Minutes)', CAST(50.00 AS Decimal(18, 2)), N'~/Content/Images/DownloadCourses/ASP.NET-Web-api-360x270.jpg')
                    INSERT INTO [dbo].[Courses] ([Id], [Header], [Description], [Price], [ImagePath]) VALUES (36, N'Bootstrap', N'Bootstrap (52 Videos & Slides - 6 Hours 27 Minutes)', CAST(50.00 AS Decimal(18, 2)), N'~/Content/Images/DownloadCourses/bootstrap-360x270.jpg')
                    INSERT INTO [dbo].[Courses] ([Id], [Header], [Description], [Price], [ImagePath]) VALUES (37, N'JQuery', N'jQuery (113 Videos & Slides - 22 Hours 41 Minutes)', CAST(50.00 AS Decimal(18, 2)), N'~/Content/Images/DownloadCourses/jquery-1-360x270.jpg')
                    INSERT INTO [dbo].[Courses] ([Id], [Header], [Description], [Price], [ImagePath]) VALUES (38, N'Dot Net Basic', N'Dot Net Basics & C#', CAST(50.00 AS Decimal(18, 2)), N'~/Content/Images/DownloadCourses/csharp-net-360x270.png')
                    INSERT INTO [dbo].[Courses] ([Id], [Header], [Description], [Price], [ImagePath]) VALUES (39, N'SQL Server', N'SQL Server & SQL Server Interview Questions & Answers', CAST(50.00 AS Decimal(18, 2)), N'~/Content/Images/DownloadCourses/MSSQLServer-360x270.png')
                    INSERT INTO [dbo].[Courses] ([Id], [Header], [Description], [Price], [ImagePath]) VALUES (40, N'ASP.NET', N'ASP.NET (172 Videos & Slides - 39 Hours 16 Minutes)', CAST(50.00 AS Decimal(18, 2)), N'~/Content/Images/DownloadCourses/aspnet-360x270.png')
                    INSERT INTO [dbo].[Courses] ([Id], [Header], [Description], [Price], [ImagePath]) VALUES (41, N'ASP.NET MVC', N'ASP.NET MVC (100 Videos & Slides - 18 Hours 6 Minutes)', CAST(50.00 AS Decimal(18, 2)), N'~/Content/Images/DownloadCourses/asp-mvc-360x270.jpg')
                    INSERT INTO [dbo].[Courses] ([Id], [Header], [Description], [Price], [ImagePath]) VALUES (42, N'ADO.NET', N'ADO.NET (21 Videos & Slides - 5 Hours 57 Minutes)', CAST(50.00 AS Decimal(18, 2)), N'~/Content/Images/DownloadCourses/ado-360x270.jpg')
                    INSERT INTO [dbo].[Courses] ([Id], [Header], [Description], [Price], [ImagePath]) VALUES (43, N'ASP.NET GridView', N'ASP.NET GridView (61 Videos & Slides - 13 Hours 27 Minutes)', CAST(50.00 AS Decimal(18, 2)), N'~/Content/Images/DownloadCourses/ASP.NET-GridView-360x270.jpg')
                    INSERT INTO [dbo].[Courses] ([Id], [Header], [Description], [Price], [ImagePath]) VALUES (44, N'Web Services', N'ASP.NET Web Services (7 Videos & Slides - 1 Hour 34 Minutes)', CAST(20.00 AS Decimal(18, 2)), N'~/Content/Images/DownloadCourses/webs-services-360x270.jpg')
                    INSERT INTO [dbo].[Courses] ([Id], [Header], [Description], [Price], [ImagePath]) VALUES (45, N'WCF', N'WCF (53 Videos & Slides - 12 Hours 1 Minute)', CAST(50.00 AS Decimal(18, 2)), N'~/Content/Images/DownloadCourses/wcfimage-360x270.png')
                    INSERT INTO [dbo].[Courses] ([Id], [Header], [Description], [Price], [ImagePath]) VALUES (46, N'Entity Framework', N'Entity Framework (25 Videos & Slides - 4 Hours 59 Minutes)', CAST(50.00 AS Decimal(18, 2)), N'~/Content/Images/DownloadCourses/Entity-Framework-360x270.jpg')
                    INSERT INTO [dbo].[Courses] ([Id], [Header], [Description], [Price], [ImagePath]) VALUES (47, N'Linq', N'LINQ, LINQ to XML and LINQ to SQL', CAST(50.00 AS Decimal(18, 2)), N'~/Content/Images/DownloadCourses/LinqToSql-360x270.jpg')
                    INSERT INTO [dbo].[Courses] ([Id], [Header], [Description], [Price], [ImagePath]) VALUES (48, N'Javascript', N'JavaScript & JavaScript with ASP.NET', CAST(50.00 AS Decimal(18, 2)), N'~/Content/Images/DownloadCourses/java-script-360x270.jpg')
                    INSERT INTO [dbo].[Courses] ([Id], [Header], [Description], [Price], [ImagePath]) VALUES (49, N'DevOps', N'Best AWS training in Bangalore | DevOps with AWS training', CAST(0.00 AS Decimal(18, 2)), N'~/Content/Images/ClassRoomCourses/devops-aws.jpg')
                    INSERT INTO [dbo].[Courses] ([Id], [Header], [Description], [Price], [ImagePath]) VALUES (50, N'MVC With Angular', N'ASP.NET Core MVC with Angular', CAST(0.00 AS Decimal(18, 2)), N'~/Content/Images/ClassRoomCourses/mvc.jpg')
                    INSERT INTO [dbo].[Courses] ([Id], [Header], [Description], [Price], [ImagePath]) VALUES (51, N'UI With Angular', N'UI Developer with Angular', CAST(0.00 AS Decimal(18, 2)), N'~/Content/Images/ClassRoomCourses/ui-dev.jpg')
                    INSERT INTO [dbo].[Courses] ([Id], [Header], [Description], [Price], [ImagePath]) VALUES (52, N'Angular 8', N'Angular 8', CAST(0.00 AS Decimal(18, 2)), N'~/Content/Images/ClassRoomCourses/angularjs8-360x270.jpg')
                    INSERT INTO [dbo].[Courses] ([Id], [Header], [Description], [Price], [ImagePath]) VALUES (53, N'Tableau', N'Tableau', CAST(0.00 AS Decimal(18, 2)), N'~/Content/Images/ClassRoomCourses/tableau.jpg')
                    INSERT INTO [dbo].[Courses] ([Id], [Header], [Description], [Price], [ImagePath]) VALUES (54, N'SalesForce', N'SalesForce', CAST(0.00 AS Decimal(18, 2)), N'~/Content/Images/ClassRoomCourses/Salesforce.jpg')
                    INSERT INTO [dbo].[Courses] ([Id], [Header], [Description], [Price], [ImagePath]) VALUES (55, N'JAVA J2EE', N'JAVA J2EE', CAST(0.00 AS Decimal(18, 2)), N'~/Content/Images/ClassRoomCourses/java-j2ee.png')
                    INSERT INTO [dbo].[Courses] ([Id], [Header], [Description], [Price], [ImagePath]) VALUES (56, N'Informatica', N'Informatica', CAST(0.00 AS Decimal(18, 2)), N'~/Content/Images/ClassRoomCourses/informatica.jpg')
                    INSERT INTO [dbo].[Courses] ([Id], [Header], [Description], [Price], [ImagePath]) VALUES (57, N'MSBI', N'MSBI', CAST(0.00 AS Decimal(18, 2)), N'~/Content/Images/ClassRoomCourses/msbi.jpg')
                    INSERT INTO [dbo].[Courses] ([Id], [Header], [Description], [Price], [ImagePath]) VALUES (58, N'Power BI', N'Power BI', CAST(0.00 AS Decimal(18, 2)), N'~/Content/Images/ClassRoomCourses/power-bi.jpg')
                    INSERT INTO [dbo].[Courses] ([Id], [Header], [Description], [Price], [ImagePath]) VALUES (59, N'ORACLE DBA', N'ORACLE DBA', CAST(0.00 AS Decimal(18, 2)), N'~/Content/Images/ClassRoomCourses/dba-360x270.jpg')
                    INSERT INTO [dbo].[Courses] ([Id], [Header], [Description], [Price], [ImagePath]) VALUES (60, N'HADOOP', N'HADOOP', CAST(0.00 AS Decimal(18, 2)), N'~/Content/Images/ClassRoomCourses/hadoop-360x270.jpg')
                    INSERT INTO [dbo].[Courses] ([Id], [Header], [Description], [Price], [ImagePath]) VALUES (61, N'IBM MQ Admin', N'IBM MQ Admin', CAST(0.00 AS Decimal(18, 2)), N'~/Content/Images/ClassRoomCourses/ibm-mq-360x270.jpg')
                    INSERT INTO [dbo].[Courses] ([Id], [Header], [Description], [Price], [ImagePath]) VALUES (62, N'ORACLE PL/SQL', N'ORACLE PL/SQL', CAST(0.00 AS Decimal(18, 2)), N'~/Content/Images/ClassRoomCourses/plsql-360x270.jpg')
                    INSERT INTO [dbo].[Courses] ([Id], [Header], [Description], [Price], [ImagePath]) VALUES (63, N'Blueprism Product Suite-5.x', N'Blueprism Product Suite-5.x', CAST(0.00 AS Decimal(18, 2)), N'~/Content/Images/ClassRoomCourses/blueprism-360x270.jpg')
                    SET IDENTITY_INSERT [dbo].[Courses] OFF
                ");

            Sql(@"
                INSERT INTO [dbo].[CourseCategories] ([CategoryId], [CourseId]) VALUES (1, 1)
                INSERT INTO [dbo].[CourseCategories] ([CategoryId], [CourseId]) VALUES (1, 2)
                INSERT INTO [dbo].[CourseCategories] ([CategoryId], [CourseId]) VALUES (1, 3)
                INSERT INTO [dbo].[CourseCategories] ([CategoryId], [CourseId]) VALUES (1, 4)
                INSERT INTO [dbo].[CourseCategories] ([CategoryId], [CourseId]) VALUES (1, 5)
                INSERT INTO [dbo].[CourseCategories] ([CategoryId], [CourseId]) VALUES (1, 6)
                INSERT INTO [dbo].[CourseCategories] ([CategoryId], [CourseId]) VALUES (1, 7)
                INSERT INTO [dbo].[CourseCategories] ([CategoryId], [CourseId]) VALUES (1, 8)
                INSERT INTO [dbo].[CourseCategories] ([CategoryId], [CourseId]) VALUES (1, 9)
                INSERT INTO [dbo].[CourseCategories] ([CategoryId], [CourseId]) VALUES (1, 10)
                INSERT INTO [dbo].[CourseCategories] ([CategoryId], [CourseId]) VALUES (1, 11)
                INSERT INTO [dbo].[CourseCategories] ([CategoryId], [CourseId]) VALUES (1, 12)
                INSERT INTO [dbo].[CourseCategories] ([CategoryId], [CourseId]) VALUES (1, 13)
                INSERT INTO [dbo].[CourseCategories] ([CategoryId], [CourseId]) VALUES (1, 14)
                INSERT INTO [dbo].[CourseCategories] ([CategoryId], [CourseId]) VALUES (1, 15)
                INSERT INTO [dbo].[CourseCategories] ([CategoryId], [CourseId]) VALUES (1, 16)
                INSERT INTO [dbo].[CourseCategories] ([CategoryId], [CourseId]) VALUES (1, 17)
                INSERT INTO [dbo].[CourseCategories] ([CategoryId], [CourseId]) VALUES (1, 18)
                INSERT INTO [dbo].[CourseCategories] ([CategoryId], [CourseId]) VALUES (1, 19)
                INSERT INTO [dbo].[CourseCategories] ([CategoryId], [CourseId]) VALUES (1, 20)
                INSERT INTO [dbo].[CourseCategories] ([CategoryId], [CourseId]) VALUES (1, 21)
                INSERT INTO [dbo].[CourseCategories] ([CategoryId], [CourseId]) VALUES (1, 22)
                INSERT INTO [dbo].[CourseCategories] ([CategoryId], [CourseId]) VALUES (2, 23)
                INSERT INTO [dbo].[CourseCategories] ([CategoryId], [CourseId]) VALUES (2, 24)
                INSERT INTO [dbo].[CourseCategories] ([CategoryId], [CourseId]) VALUES (2, 25)
                INSERT INTO [dbo].[CourseCategories] ([CategoryId], [CourseId]) VALUES (2, 26)
                INSERT INTO [dbo].[CourseCategories] ([CategoryId], [CourseId]) VALUES (2, 27)
                INSERT INTO [dbo].[CourseCategories] ([CategoryId], [CourseId]) VALUES (2, 28)
                INSERT INTO [dbo].[CourseCategories] ([CategoryId], [CourseId]) VALUES (2, 29)
                INSERT INTO [dbo].[CourseCategories] ([CategoryId], [CourseId]) VALUES (2, 30)
                INSERT INTO [dbo].[CourseCategories] ([CategoryId], [CourseId]) VALUES (2, 31)
                INSERT INTO [dbo].[CourseCategories] ([CategoryId], [CourseId]) VALUES (2, 32)
                INSERT INTO [dbo].[CourseCategories] ([CategoryId], [CourseId]) VALUES (2, 33)
                INSERT INTO [dbo].[CourseCategories] ([CategoryId], [CourseId]) VALUES (2, 34)
                INSERT INTO [dbo].[CourseCategories] ([CategoryId], [CourseId]) VALUES (2, 35)
                INSERT INTO [dbo].[CourseCategories] ([CategoryId], [CourseId]) VALUES (2, 36)
                INSERT INTO [dbo].[CourseCategories] ([CategoryId], [CourseId]) VALUES (2, 37)
                INSERT INTO [dbo].[CourseCategories] ([CategoryId], [CourseId]) VALUES (2, 38)
                INSERT INTO [dbo].[CourseCategories] ([CategoryId], [CourseId]) VALUES (2, 39)
                INSERT INTO [dbo].[CourseCategories] ([CategoryId], [CourseId]) VALUES (2, 40)
                INSERT INTO [dbo].[CourseCategories] ([CategoryId], [CourseId]) VALUES (2, 41)
                INSERT INTO [dbo].[CourseCategories] ([CategoryId], [CourseId]) VALUES (2, 42)
                INSERT INTO [dbo].[CourseCategories] ([CategoryId], [CourseId]) VALUES (2, 43)
                INSERT INTO [dbo].[CourseCategories] ([CategoryId], [CourseId]) VALUES (2, 44)
                INSERT INTO [dbo].[CourseCategories] ([CategoryId], [CourseId]) VALUES (2, 45)
                INSERT INTO [dbo].[CourseCategories] ([CategoryId], [CourseId]) VALUES (2, 46)
                INSERT INTO [dbo].[CourseCategories] ([CategoryId], [CourseId]) VALUES (2, 47)
                INSERT INTO [dbo].[CourseCategories] ([CategoryId], [CourseId]) VALUES (2, 48)
                INSERT INTO [dbo].[CourseCategories] ([CategoryId], [CourseId]) VALUES (3, 49)
                INSERT INTO [dbo].[CourseCategories] ([CategoryId], [CourseId]) VALUES (3, 50)
                INSERT INTO [dbo].[CourseCategories] ([CategoryId], [CourseId]) VALUES (3, 51)
                INSERT INTO [dbo].[CourseCategories] ([CategoryId], [CourseId]) VALUES (3, 52)
                INSERT INTO [dbo].[CourseCategories] ([CategoryId], [CourseId]) VALUES (3, 53)
                INSERT INTO [dbo].[CourseCategories] ([CategoryId], [CourseId]) VALUES (3, 54)
                INSERT INTO [dbo].[CourseCategories] ([CategoryId], [CourseId]) VALUES (3, 55)
                INSERT INTO [dbo].[CourseCategories] ([CategoryId], [CourseId]) VALUES (3, 56)
                INSERT INTO [dbo].[CourseCategories] ([CategoryId], [CourseId]) VALUES (3, 57)
                INSERT INTO [dbo].[CourseCategories] ([CategoryId], [CourseId]) VALUES (3, 58)
                INSERT INTO [dbo].[CourseCategories] ([CategoryId], [CourseId]) VALUES (3, 59)
                INSERT INTO [dbo].[CourseCategories] ([CategoryId], [CourseId]) VALUES (3, 60)
                INSERT INTO [dbo].[CourseCategories] ([CategoryId], [CourseId]) VALUES (3, 61)
                INSERT INTO [dbo].[CourseCategories] ([CategoryId], [CourseId]) VALUES (3, 62)
                INSERT INTO [dbo].[CourseCategories] ([CategoryId], [CourseId]) VALUES (3, 63)
               ");

            Sql(@"
                SET IDENTITY_INSERT [dbo].[Subscribers] ON
                INSERT INTO [dbo].[Subscribers] ([Id], [Email]) VALUES (1, N'ibrahimelbatal2@gmail.com')
                SET IDENTITY_INSERT [dbo].[Subscribers] OFF
            ");

            Sql(@"
                SET IDENTITY_INSERT [dbo].[CourseDetailsHeaders] ON
                INSERT INTO [dbo].[CourseDetailsHeaders] ([Id], [Header], [CourseId]) VALUES (1, N'Part 1 - What is DevOps', 49)
                INSERT INTO [dbo].[CourseDetailsHeaders] ([Id], [Header], [CourseId]) VALUES (2, N'Part 2 - DevOps deep dive and importance in agile development ', 49)
                INSERT INTO [dbo].[CourseDetailsHeaders] ([Id], [Header], [CourseId]) VALUES (3, N'part 3 - Who can become devops developer', 49)
                INSERT INTO [dbo].[CourseDetailsHeaders] ([Id], [Header], [CourseId]) VALUES (4, N'Part 4 - Git and GitHub Introduction', 49)
                INSERT INTO [dbo].[CourseDetailsHeaders] ([Id], [Header], [CourseId]) VALUES (5, N'Part 5 - Configure Git on Windows,Understand git clone,pull,private and public repos.', 49)
                INSERT INTO [dbo].[CourseDetailsHeaders] ([Id], [Header], [CourseId]) VALUES (6, N'DevOps Introduction', 49)
                INSERT INTO [dbo].[CourseDetailsHeaders] ([Id], [Header], [CourseId]) VALUES (7, N'Linux Commands Shell Scripting', 49)
                INSERT INTO [dbo].[CourseDetailsHeaders] ([Id], [Header], [CourseId]) VALUES (8, N'Introduction to ASP.NET MVC', 50)
                INSERT INTO [dbo].[CourseDetailsHeaders] ([Id], [Header], [CourseId]) VALUES (9, N'HTML5', 50)
                INSERT INTO [dbo].[CourseDetailsHeaders] ([Id], [Header], [CourseId]) VALUES (10, N'Getting started with ASP.NET MVC', 50)
                INSERT INTO [dbo].[CourseDetailsHeaders] ([Id], [Header], [CourseId]) VALUES (11, N'Creating a Complete ASP.NET MVC Application', 50)
                INSERT INTO [dbo].[CourseDetailsHeaders] ([Id], [Header], [CourseId]) VALUES (12, N'Using Razor View Engine', 50)
                INSERT INTO [dbo].[CourseDetailsHeaders] ([Id], [Header], [CourseId]) VALUES (13, N'URL Routing', 50)
                INSERT INTO [dbo].[CourseDetailsHeaders] ([Id], [Header], [CourseId]) VALUES (14, N'Controllers and actions ', 50)
                INSERT INTO [dbo].[CourseDetailsHeaders] ([Id], [Header], [CourseId]) VALUES (15, N'Html Intoduction', 51)
                INSERT INTO [dbo].[CourseDetailsHeaders] ([Id], [Header], [CourseId]) VALUES (16, N'Html Document Head', 51)
                INSERT INTO [dbo].[CourseDetailsHeaders] ([Id], [Header], [CourseId]) VALUES (17, N'Html Body', 51)
                INSERT INTO [dbo].[CourseDetailsHeaders] ([Id], [Header], [CourseId]) VALUES (18, N'Links / Anchor tags', 51)
                INSERT INTO [dbo].[CourseDetailsHeaders] ([Id], [Header], [CourseId]) VALUES (19, N'Html Lists', 51)
                INSERT INTO [dbo].[CourseDetailsHeaders] ([Id], [Header], [CourseId]) VALUES (20, N'Table', 51)
                INSERT INTO [dbo].[CourseDetailsHeaders] ([Id], [Header], [CourseId]) VALUES (21, N'Images and objects', 51)
                INSERT INTO [dbo].[CourseDetailsHeaders] ([Id], [Header], [CourseId]) VALUES (22, N'Course Duration', 52)
                INSERT INTO [dbo].[CourseDetailsHeaders] ([Id], [Header], [CourseId]) VALUES (23, N'Prerequistes', 52)
                INSERT INTO [dbo].[CourseDetailsHeaders] ([Id], [Header], [CourseId]) VALUES (24, N'Learning outcomes:', 52)
                INSERT INTO [dbo].[CourseDetailsHeaders] ([Id], [Header], [CourseId]) VALUES (25, N'Hands-on projects:', 52)
                INSERT INTO [dbo].[CourseDetailsHeaders] ([Id], [Header], [CourseId]) VALUES (26, N'Course Highlights', 53)
                INSERT INTO [dbo].[CourseDetailsHeaders] ([Id], [Header], [CourseId]) VALUES (27, N'Main Areas in the Syllabus', 53)
                INSERT INTO [dbo].[CourseDetailsHeaders] ([Id], [Header], [CourseId]) VALUES (28, N'Introduction', 54)
                INSERT INTO [dbo].[CourseDetailsHeaders] ([Id], [Header], [CourseId]) VALUES (29, N'Admin Manage Users', 54)
                INSERT INTO [dbo].[CourseDetailsHeaders] ([Id], [Header], [CourseId]) VALUES (30, N'Company Profile', 54)
                INSERT INTO [dbo].[CourseDetailsHeaders] ([Id], [Header], [CourseId]) VALUES (31, N'Core Java', 55)
                INSERT INTO [dbo].[CourseDetailsHeaders] ([Id], [Header], [CourseId]) VALUES (32, N'File Management', 55)
                INSERT INTO [dbo].[CourseDetailsHeaders] ([Id], [Header], [CourseId]) VALUES (33, N'Threads', 55)
                INSERT INTO [dbo].[CourseDetailsHeaders] ([Id], [Header], [CourseId]) VALUES (34, N'JDBC(Java Database Connectivity)', 55)
                INSERT INTO [dbo].[CourseDetailsHeaders] ([Id], [Header], [CourseId]) VALUES (35, N'Servlets', 55)
                INSERT INTO [dbo].[CourseDetailsHeaders] ([Id], [Header], [CourseId]) VALUES (36, N'Introduction To MS-BI', 57)
                INSERT INTO [dbo].[CourseDetailsHeaders] ([Id], [Header], [CourseId]) VALUES (37, N'Introduction to SSIS', 57)
                INSERT INTO [dbo].[CourseDetailsHeaders] ([Id], [Header], [CourseId]) VALUES (38, N'Introduction to Sql Server Reporting Services', 57)
                INSERT INTO [dbo].[CourseDetailsHeaders] ([Id], [Header], [CourseId]) VALUES (39, N'Creating Reports', 57)
                INSERT INTO [dbo].[CourseDetailsHeaders] ([Id], [Header], [CourseId]) VALUES (40, N'Data Ware Housing Concepts', 56)
                INSERT INTO [dbo].[CourseDetailsHeaders] ([Id], [Header], [CourseId]) VALUES (41, N'Oracle Concepts', 56)
                INSERT INTO [dbo].[CourseDetailsHeaders] ([Id], [Header], [CourseId]) VALUES (42, N'Learning PowerPivot', 58)
                INSERT INTO [dbo].[CourseDetailsHeaders] ([Id], [Header], [CourseId]) VALUES (43, N'Advanced DAX functions', 58)
                INSERT INTO [dbo].[CourseDetailsHeaders] ([Id], [Header], [CourseId]) VALUES (44, N'Introduction to Database', 59)
                INSERT INTO [dbo].[CourseDetailsHeaders] ([Id], [Header], [CourseId]) VALUES (45, N'Oracle Architecture', 59)
                INSERT INTO [dbo].[CourseDetailsHeaders] ([Id], [Header], [CourseId]) VALUES (46, N'Database Creation', 59)
                INSERT INTO [dbo].[CourseDetailsHeaders] ([Id], [Header], [CourseId]) VALUES (47, N'Tablespace Management', 59)
                INSERT INTO [dbo].[CourseDetailsHeaders] ([Id], [Header], [CourseId]) VALUES (48, N'Storage parameters', 59)
                INSERT INTO [dbo].[CourseDetailsHeaders] ([Id], [Header], [CourseId]) VALUES (49, N'Oracle Architecture (Basic to Modirate)', 62)
                INSERT INTO [dbo].[CourseDetailsHeaders] ([Id], [Header], [CourseId]) VALUES (50, N'SQL (Beginers to advance)', 62)
                INSERT INTO [dbo].[CourseDetailsHeaders] ([Id], [Header], [CourseId]) VALUES (51, N'Big Data & Hadoop', 60)
                INSERT INTO [dbo].[CourseDetailsHeaders] ([Id], [Header], [CourseId]) VALUES (52, N'Hadoop Distributed File System', 60)
                INSERT INTO [dbo].[CourseDetailsHeaders] ([Id], [Header], [CourseId]) VALUES (53, N'IBM MQ Admin Assessment Topics', 61)
                INSERT INTO [dbo].[CourseDetailsHeaders] ([Id], [Header], [CourseId]) VALUES (54, N'Point-To-Point Communication', 61)
                INSERT INTO [dbo].[CourseDetailsHeaders] ([Id], [Header], [CourseId]) VALUES (55, N'Foundation trainning', 63)
                INSERT INTO [dbo].[CourseDetailsHeaders] ([Id], [Header], [CourseId]) VALUES (56, N'Blueprism software Plateform', 63)
                INSERT INTO [dbo].[CourseDetailsHeaders] ([Id], [Header], [CourseId]) VALUES (1054, N'What is bootstrap', 4)
                INSERT INTO [dbo].[CourseDetailsHeaders] ([Id], [Header], [CourseId]) VALUES (1055, N'Setting up bootstrap', 4)
                INSERT INTO [dbo].[CourseDetailsHeaders] ([Id], [Header], [CourseId]) VALUES (1056, N'Bootstrap Grid System', 4)
                INSERT INTO [dbo].[CourseDetailsHeaders] ([Id], [Header], [CourseId]) VALUES (1057, N'Bootstrap 3 grid classes', 4)
                INSERT INTO [dbo].[CourseDetailsHeaders] ([Id], [Header], [CourseId]) VALUES (1058, N'Introduction to Web Services', 11)
                INSERT INTO [dbo].[CourseDetailsHeaders] ([Id], [Header], [CourseId]) VALUES (1059, N'Consuming a Web Service', 11)
                INSERT INTO [dbo].[CourseDetailsHeaders] ([Id], [Header], [CourseId]) VALUES (1060, N'Using session state in a Web Service', 11)
                INSERT INTO [dbo].[CourseDetailsHeaders] ([Id], [Header], [CourseId]) VALUES (1061, N'WebMethod attribute properties', 11)
                INSERT INTO [dbo].[CourseDetailsHeaders] ([Id], [Header], [CourseId]) VALUES (1062, N'WebMethod overloading in web services', 11)
                INSERT INTO [dbo].[CourseDetailsHeaders] ([Id], [Header], [CourseId]) VALUES (1063, N'Calling asp.net web service from javascript using ajax', 11)
                INSERT INTO [dbo].[CourseDetailsHeaders] ([Id], [Header], [CourseId]) VALUES (1064, N'Real time example of calling live weather forecast web service', 11)
                INSERT INTO [dbo].[CourseDetailsHeaders] ([Id], [Header], [CourseId]) VALUES (1065, N'Angular Project Setup', 3)
                INSERT INTO [dbo].[CourseDetailsHeaders] ([Id], [Header], [CourseId]) VALUES (1066, N'Angular Project Setup', 3)
                SET IDENTITY_INSERT [dbo].[CourseDetailsHeaders] OFF
            ");

            Sql(@"
                SET IDENTITY_INSERT [dbo].[CourseDetailsBodies] ON
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (1, N'Understand what DevOps is and Various DevOps and thier usage with real time example', 1)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (2, N'Understand DevOps in detail.', 2)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (3, N'What is waterfall development methodology', 2)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (4, N'what is agile development methodology.', 2)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (5, N'importance of devops.', 2)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (6, N'future of devops.', 2)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (7, N'Devops job opportunities.', 2)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (8, N'Who can learn DevOps and become a DevOps engineer.', 3)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (9, N'what are the pre-requisites to learn DevOps.', 3)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (10, N'what skills are required for DevOps engineer.', 3)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (11, N'tools required for DevOps engineer.', 3)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (12, N'Understand what is Source code management.', 4)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (13, N'Understand what is version controlling systems.', 4)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (14, N'Create an account on GitHub.', 4)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (15, N'How to configure git on windows', 5)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (16, N'what are git clone and pull commands and how to use them.', 5)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (17, N'what are public and private repositories.', 5)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (18, N'How to create public and private repos and their difference ', 5)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (19, N'Understand development.', 6)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (20, N'development SDLC:Water Fall vs Agile ', 6)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (21, N'What is DevOps', 6)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (22, N'DevOps SDLC', 6)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (23, N'DevOps Tools For DevOps SDLC', 6)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (24, N'DevOps Roles and Resposibilites', 6)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (25, N'Basic Programming using Shell Scripting', 7)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (26, N'Creating Functions and its advantages', 7)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (27, N'working with if,else,for loop,while loop,and switch cases', 7)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (28, N'Breif History of Web Application Development', 8)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (29, N'What is wrong with ASP,NET Web Forms', 8)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (30, N'Web Development today', 8)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (31, N'Key Benefits Of ASP.NET MVC ', 8)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (32, N'Who hould use ASP.NET MVC', 8)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (33, N'Introduction to Html5', 9)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (34, N'Html5 new elements', 9)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (35, N'Canvas', 9)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (36, N'Vedio and Audio', 9)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (37, N'Web Storage', 9)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (38, N'Geolocation ,Offline web Pages', 9)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (39, N'ASP.NET MVC Project Templates', 10)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (40, N'Understanding the structure of an ASP.NET MVC Project', 10)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (41, N'Naming Convension', 10)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (42, N'Creating Views', 10)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (43, N'Defining Controllers', 10)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (44, N'Defining a data model', 10)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (45, N'Creating strongly-typed views', 11)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (46, N'Understanding URL and action methods', 11)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (47, N'Using html helpers', 11)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (48, N'Handling form post-backs', 11)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (49, N'Data validation', 11)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (50, N'Razor design tools', 12)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (51, N'implementing a Razor View', 12)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (52, N'Razor syntax', 12)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (53, N'Accessing model data in Razor views', 12)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (54, N'working with layouts', 12)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (55, N'using razor expressions', 12)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (56, N'Introducing URL Pattern', 13)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (57, N'Creating and Registering a Simple route', 13)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (58, N'Defining Default values and using static URL segments', 13)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (59, N'constraining Routes', 13)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (60, N'BYpassing the Routing System', 13)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (61, N'Intoducing the controller', 14)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (62, N'reciveing inputs', 14)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (63, N'producing output', 14)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (64, N'Elements', 15)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (65, N'Attributes', 15)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (66, N'Title', 16)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (67, N'Meta Tag', 16)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (68, N'Charset', 16)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (69, N'Style Tag', 16)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (70, N'Script Tag', 16)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (71, N'Link Tag', 16)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (72, N'Base tag', 16)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (73, N'What is semantic', 17)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (74, N'Block vs Inline elements ', 17)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (75, N'Text format', 17)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (76, N'Header tag', 17)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (77, N'Target,title attributes', 18)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (78, N'Relative vs absolute', 18)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (79, N'Id links and external id links', 18)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (80, N'Access keys', 18)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (81, N'UnOrdered Lists', 19)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (82, N'Ordered Lists', 19)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (83, N'Definition list', 19)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (84, N'Nested List', 19)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (85, N'Table Structure', 20)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (86, N'Sematic Table Structure', 20)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (87, N'Rows - Columns', 20)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (88, N'Col Span', 20)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (89, N'Row Span', 20)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (90, N'Cell Padding,Cell Spacing', 20)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (91, N'Borders and formatting table', 20)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (92, N'Embedding images', 21)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (93, N'Working With transparent images', 21)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (94, N'Embedding Vedio audio', 21)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (95, N'Object tag with params', 21)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (96, N'1 Total duration - 40+ hours (5 days)', 22)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (97, N'Basic Html and CSS', 23)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (98, N'Knowledge of javascript', 23)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (99, N'Web develpment is experience is good to have', 23)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (100, N'Understand Angular key features', 24)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (101, N'Learn about the Data Flow and usage with Angular', 24)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (102, N'Implementing Bootstrap and CSS to style Angular app', 24)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (103, N'Identify the right set of structures and state containers for your angular application', 24)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (104, N'manage data by using of angular', 24)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (105, N'learn how to handle events and execute angular''s router', 24)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (106, N'Implementing server-side rendering for SEO benifits and to reduce initial load times', 24)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (107, N'Create,build,and deploy a angular application using the angular cli', 24)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (108, N'develop dynamic model-driven forms that are easier to unit test', 24)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (109, N'Projects on each module covered in this course', 25)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (110, N'Angular project : Bulid an end-to-end WebApp', 25)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (111, N'Faculty : Working as Technical Architect with 14 year of Real Time experience', 26)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (112, N'Course Duration : 60 Hours', 26)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (113, N'Real Time Scenarios', 26)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (114, N'Business Case studies with Live Examles', 26)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (115, N'Interview Questions walkthrough and resume preparation', 26)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (116, N'Mock Interviews', 26)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (117, N'Tableau Desktop', 27)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (118, N'Tableau Server', 27)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (119, N'Data Visualization', 27)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (120, N'Complete Hands-on training on oracle-SQL as Complementary', 27)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (121, N'Data Modeling with real time scenarios', 27)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (122, N' CRM Overview', 28)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (123, N'Intoduction To CRM?', 28)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (124, N'Creating sales force ACCOUNT', 28)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (125, N'Users', 29)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (126, N'Mass Email Users', 29)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (127, N'Roles', 29)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (128, N'Permission Sets', 29)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (129, N'Profiles', 29)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (130, N'Public Groups', 29)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (131, N'Queues', 29)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (132, N'Company Information', 30)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (133, N'Fiscal Year', 30)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (134, N'Business Hours', 30)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (135, N'Holidays', 30)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (136, N'Language Settings', 30)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (137, N'Introduction to java', 31)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (138, N'Features of Java', 31)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (139, N'Java Environment Setup', 31)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (140, N'OOPS Concepts', 31)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (141, N'Data Types', 31)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (142, N'Local Variables, Instance variable', 31)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (143, N'Static Variables,Static Block,Static Method,Static Class', 31)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (144, N'Access Specifiers , Access Modifiers', 31)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (145, N'Operators', 31)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (146, N'Controll Statement', 31)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (147, N'Arrays', 31)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (148, N'String,String Buffer,String Builder', 31)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (149, N'Interfaces,Abstract and Concrete Classes', 31)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (150, N'Packages', 31)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (151, N'Exception Handling', 31)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (152, N'Garbage Collection', 31)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (153, N'Inner Classes', 31)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (154, N'Annotations.3', 31)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (155, N'Generic Types', 31)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (156, N'Serialization', 31)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (157, N'Character/Byte Streams', 32)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (158, N'Creating File,Directories', 32)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (159, N'Thread Life Cycle & implementing Threads', 33)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (160, N'Synchronization', 33)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (161, N'Thread Communication', 33)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (162, N'JDBC Features', 34)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (163, N'Types Of Drivers', 34)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (164, N'Driver Manager', 34)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (165, N'Connection', 34)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (166, N'Statement', 34)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (167, N'Prepared Statement', 34)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (168, N'Callable Statement', 34)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (169, N'Result Set', 34)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (170, N'ResultSet MetaData', 34)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (171, N'Overview of Servlets', 35)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (172, N'Web Application Architecture', 35)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (173, N'Tomcat Overview', 35)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (174, N'Servlet Life Cycle', 35)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (175, N'Type of Servlets', 35)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (176, N'Servlets Config & Context', 35)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (177, N'Session Management', 35)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (178, N'Request Dispatcher(Forward,Include)', 35)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (179, N'Send Redirect', 35)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (180, N'Filters', 35)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (181, N'Request & Response headers', 35)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (182, N'Web Application Deployment', 35)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (183, N'What is MS-BI', 36)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (184, N'BI/DWF life Cycle', 36)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (185, N'ETL and OLAP Tools', 36)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (186, N'Features of MS-BI', 36)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (187, N'Package', 37)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (188, N'Tasks', 37)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (189, N'SSIS installation', 37)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (190, N'SSIS Architecture', 37)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (191, N'SSIS Wizard', 37)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (192, N'Control Flow Tasks', 37)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (193, N'Data flow Tasks', 37)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (194, N'Variables and Expressions', 37)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (195, N'Errors and Debugging SSIS', 37)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (196, N'Data Viewers', 37)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (197, N'Deployment', 37)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (198, N'Manually Executing SSIS package', 37)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (199, N'Scheduling SSIS package', 37)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (200, N'Importing and Exporting Packages', 37)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (201, N'Monitoring and optimizing Package', 37)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (202, N'Reporting Services Architecture', 38)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (203, N'Reporting Services Terminology', 38)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (204, N'Deconstructing Reporting Services', 39)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (205, N'Shared Data Sources', 39)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (206, N'Creating Reports from Scratch', 39)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (207, N'Introduction to Data Warehousing', 40)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (208, N'Introduction to OLTP,ETL and OLAP Systems', 40)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (209, N'Life Cycle', 40)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (210, N'Data Modeling', 40)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (211, N'Normalization Forms', 40)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (212, N'Dimensional Modeling', 40)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (213, N'Satr schema', 40)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (214, N'Snowflake Schema', 40)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (215, N'Types of Fact and Dimension Tables', 40)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (216, N'Introduction to oracle', 41)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (217, N'Data Types', 41)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (218, N'Constraints', 41)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (219, N'Select Statement Usage', 41)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (220, N'Joins', 41)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (221, N'Sub Queries', 41)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (222, N'Performance Tuning Tips & Tricks', 41)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (223, N'What is PowerPivot for Excel', 42)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (224, N'Importing Your data PowerPivot', 42)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (225, N'Creating PowerPivot data model', 42)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (226, N'Creating PowerTables with PowerPivot', 42)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (227, N'Creating a Data Table', 42)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (228, N'Using Sclicers to filter Data', 42)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (229, N'Connecting Sclicers to more than one pivotTable', 42)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (230, N'Using Charts and sclicers to create interactive Dashboards', 42)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (231, N'Using DAX in PowerPivot', 42)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (232, N'Creating Calculated Columns', 42)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (233, N'Creating Calculated Fiels', 42)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (234, N'Implicit and explicit Calculated Fiels', 42)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (235, N'Using DAX aggregate Functions in a PowerPivot Table', 42)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (236, N'Using Count Rows and Distinct Count Function', 42)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (237, N'The Difference between evaluations using Row Context and evaluations using Filter context', 42)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (238, N'SUMX and CALCULATE', 43)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (239, N'Time Intelligence Functions', 43)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (240, N'Creating Key Performance Indicators', 43)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (241, N'Using PowerPivot Sets', 43)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (242, N'Different Types Of Databases', 44)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (243, N'Oracle 9i/10g/11g features', 44)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (244, N'Responsibilities of DBA', 44)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (245, N'Physical Structure', 45)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (246, N'Logical Structure', 45)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (247, N'Instance', 45)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (248, N'System Global Area-SGA', 45)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (249, N'Program Global Area PGA', 45)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (250, N'Background Processes', 45)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (251, N'DB Creation steps', 46)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (252, N'SYSAUX TableSpace', 46)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (253, N'Additional Tablespaces', 47)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (254, N'Advantages of having different tablespaces', 47)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (255, N'Types of tablespaces', 47)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (256, N'Bigfile tablespace', 47)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (257, N'Temporary tablespace', 47)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (258, N'Automatic Segment Space management', 48)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (259, N'Data dictionary Views', 48)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (260, N'What is Oracle database server', 49)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (261, N'Connecting to database instance in dedicated server mode', 49)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (262, N'Connecting to database instance in Shared server mode', 49)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (263, N'Introduction to file structure in database', 49)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (264, N'introduction to Oracle Memory Structure (SGA,PGA,UGA)', 49)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (265, N'Oracle shared pools Java pool,Large pool ,streem pool,etc', 49)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (266, N'Introduction to Oracle''s Processes(Server,background,Slave)', 49)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (267, N'Oracle database server installing scenarios', 49)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (268, N'Hardware Consideration for installing Oracle Database', 49)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (269, N'What is transaction in context of RDBMS(Atomicity,Durability,Consistancy,Isolation)', 49)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (270, N'Distributed Transaction', 49)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (271, N'Autonomous Transaction', 49)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (272, N'What is Locking?(Optimistic,pessimistic)', 49)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (273, N'What is blocking in oracle', 49)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (274, N'Types odf DDl Lock in oracle', 49)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (275, N'Types of Lock and Latches in Oracle', 49)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (276, N'How Commit and Rollback Work in oracle', 49)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (277, N'Undo management in Orackle', 49)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (278, N'Common Performance Issues in Redo Log', 49)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (279, N'Oracle Storage Termonology', 49)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (280, N'High water mark and free lists', 49)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (281, N'Oracle storage parameters (PCTFREE,PCTUSED,INITTRANS,MAXTRANS,INTIAL,NEXT,PVTINCREASE)', 49)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (282, N'What is Sql and Why Learn Sql', 50)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (283, N'An Intro To Database', 50)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (284, N'DBMS vs RDBMS and RDBMS vs ORDBMS', 50)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (285, N'An Intro To SQL*Plus', 50)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (286, N'The Sql Execution Environment', 50)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (287, N'The Where and Order By Clause', 50)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (288, N'System Defined Functions', 50)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (289, N'Reading Syntax Diagrams', 50)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (290, N'Date and Convension Functions', 50)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (291, N'Aggregate Function ,GROUP BY,and HAVING Clauses', 50)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (292, N'Simple and Complex Joins', 50)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (293, N'SubQueries (Simple,Co-related,Scalar,inline-view)', 50)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (294, N'Insert , Upate , Delete(DML)', 50)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (295, N'Create,Alter,and Drop tables(DDL)', 50)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (296, N'Indexex ,sequences and Views', 50)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (297, N'The Data Ductionary,Scripting,and Reporting', 50)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (298, N'Users,Privilages,and Synonyms', 50)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (299, N'Regular expression and Hierarchical Queries', 50)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (300, N'What is Big Bata', 51)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (301, N'Sources Of Big Data', 51)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (302, N'IBM Definition For Big Data', 51)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (303, N'Definition Of Hadoop', 51)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (304, N'History of Hadoop', 51)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (305, N'Features Of Hadoop', 51)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (306, N'Hadoop Eco-System', 51)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (307, N'Other Hadoop Related Products Of Apache', 51)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (308, N'Distributed File System', 52)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (309, N'Defination Of HDFS', 52)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (310, N'Where not to use HDFS', 52)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (311, N'HFDS Concepts', 52)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (312, N'Hadoop Architecture', 52)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (313, N'NameNode,DataNode,SNN', 52)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (314, N'HDFS Federation', 52)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (315, N'HDFS High Avialbilty', 52)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (316, N'Hadoop Io Operation (Read,Write)', 52)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (317, N'HDFS Rack Awareness', 52)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (318, N'Hadoop Modes', 52)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (319, N'Hadoop Configuration', 52)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (320, N'Linux & Hadoop Commands', 52)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (321, N'Introduction to MQ', 53)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (322, N'Installation of MQ/UnInstallation Of Mq /Maintinance Appy & Migration on Linux', 53)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (323, N'MQ Object Overview', 53)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (324, N'Types Of queus', 53)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (325, N'What is Message & Predefined Message Types', 53)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (326, N'Types Of Persistence', 53)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (327, N'Basic DQM Setup Configuration On Distributed Systems', 54)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (328, N'Chanel Sharing (or) Xmitq Sharing', 54)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (329, N'One-to-many Communication', 54)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (330, N'many-to-one Communication', 54)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (331, N'Troubleshooting steps', 54)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (332, N'Types of predefine MCAS', 54)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (333, N'Logical Combinations on Message Channel', 54)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (334, N'Channel States & Channel Properties', 54)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (335, N'RPA overview', 55)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (336, N'BP overview', 55)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (337, N'Basic Installation and Configuration ', 55)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (338, N'Basic Operations and all stages in BP', 55)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (339, N'Error Management', 55)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (340, N'Web Automation', 55)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (341, N'Window Automation', 55)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (342, N'Db Automation', 55)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (343, N'Email Automation', 55)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (344, N'Case(Queue) Management', 55)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (345, N'Object Studio', 56)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (346, N'Application Modular', 56)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (347, N'Process Studio', 56)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (348, N'Control Room', 56)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (349, N'Release Manage.', 56)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (350, N'Dashboard', 56)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (351, N'System manager', 56)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (1327, N'http://csharp-video-tutorials.blogspot.com/2016/05/what-is-bootstrap.html', 1054)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (1328, N'http://csharp-video-tutorials.blogspot.com/2016/05/what-is-bootstrap_3.html', 1054)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (1329, N'http://csharp-video-tutorials.blogspot.com/2016/05/setting-up-bootstrap.html', 1055)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (1330, N'http://csharp-video-tutorials.blogspot.com/2016/05/setting-up-bootstrap_6.html', 1055)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (1331, N'https://www.youtube.com/watch?v=6e9IlNJ6W38&list=PL6n9fhu94yhXd4xnk-j5FGhHjUv1LsF0V&index=2', 1055)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (1332, N'http://csharp-video-tutorials.blogspot.com/2016/05/bootstrap-grid-system.html', 1056)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (1333, N'http://csharp-video-tutorials.blogspot.com/2016/05/bootstrap-grid-system_16.html', 1056)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (1334, N'http://csharp-video-tutorials.blogspot.com/2016/05/bootstrap-3-grid-classes_17.html', 1057)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (1335, N'http://csharp-video-tutorials.blogspot.com/2016/05/bootstrap-3-grid-classes_99.html', 1057)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (1336, N'https://www.youtube.com/watch?v=lAh2uPzoGyg&list=PL6n9fhu94yhXd4xnk-j5FGhHjUv1LsF0V&index=4', 1057)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (1337, N'https://www.youtube.com/watch?v=314m7YBRFvQ&list=PL6n9fhu94yhXd4xnk-j5FGhHjUv1LsF0V&index=1', 1054)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (1339, N'https://www.youtube.com/watch?v=GDwWmrpCa30&list=PL6n9fhu94yhXd4xnk-j5FGhHjUv1LsF0V&index=3', 1056)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (1340, N'http://csharp-video-tutorials.blogspot.com/2013/11/part-1-introduction-to-aspnet-web.html', 1058)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (1341, N'http://csharp-video-tutorials.blogspot.com/2013/11/part-1-introduction-to-aspnet-web_11.html', 1058)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (1342, N'https://www.youtube.com/watch?v=xzJm0lPIoJY&index=1&list=PL6n9fhu94yhW6VEqiXQvS2bLb5KaLTo7c', 1058)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (1343, N'http://csharp-video-tutorials.blogspot.com/2013/11/part-2-consuming-web-service.html', 1059)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (1344, N'http://csharp-video-tutorials.blogspot.com/2013/11/part-2-consuming-web-service_11.html', 1059)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (1345, N'https://www.youtube.com/watch?v=ycKnYOlQDEE&index=2&list=PL6n9fhu94yhW6VEqiXQvS2bLb5KaLTo7c', 1059)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (1346, N'http://csharp-video-tutorials.blogspot.com/2013/11/part-3-using-aspnet-session-state-in.html', 1060)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (1347, N'http://csharp-video-tutorials.blogspot.com/2013/11/part-3-using-aspnet-session-state-in_11.html', 1060)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (1348, N'https://www.youtube.com/watch?v=gq1Yt11brps&index=3&list=PL6n9fhu94yhW6VEqiXQvS2bLb5KaLTo7c', 1060)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (1349, N'http://csharp-video-tutorials.blogspot.com/2013/11/part-4-webmethod-attribute-properties.html', 1061)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (1350, N'http://csharp-video-tutorials.blogspot.com/2013/11/part-4-webmethod-attribute-properties_11.html', 1061)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (1351, N'https://www.youtube.com/watch?v=lyse8HFVTcM&index=4&list=PL6n9fhu94yhW6VEqiXQvS2bLb5KaLTo7c', 1061)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (1352, N'http://csharp-video-tutorials.blogspot.com/2013/11/part-5-webmethod-overloading-in-aspnet.html', 1062)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (1353, N'http://csharp-video-tutorials.blogspot.com/2013/11/part-5-webmethod-overloading-in-aspnet_11.html', 1062)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (1354, N'https://www.youtube.com/watch?v=EkCvoHg8OX8&index=5&list=PL6n9fhu94yhW6VEqiXQvS2bLb5KaLTo7c', 1062)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (1355, N'http://csharp-video-tutorials.blogspot.com/2013/11/part-6-calling-aspnet-web-service-from.html', 1063)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (1356, N'http://csharp-video-tutorials.blogspot.com/2013/11/part-6-calling-aspnet-web-service-from_12.html', 1063)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (1357, N'https://www.youtube.com/watch?v=-xMGwiV5A6o&index=6&list=PL6n9fhu94yhW6VEqiXQvS2bLb5KaLTo7c', 1063)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (1358, N'http://csharp-video-tutorials.blogspot.com/2013/11/part-7-real-time-example-of-calling_13.html', 1064)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (1359, N'http://csharp-video-tutorials.blogspot.com/2013/11/part-7-real-time-example-of-calling.html', 1064)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (1360, N'https://www.youtube.com/watch?v=0BXL-I-bxO4&index=7&list=PL6n9fhu94yhW6VEqiXQvS2bLb5KaLTo7c', 1064)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (1361, N'http://csharp-video-tutorials.blogspot.com/2017/12/angular-project-setup.html', 1065)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (1362, N'http://csharp-video-tutorials.blogspot.com/2017/12/angular-project-setup-slides.html', 1065)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (1363, N'https://www.youtube.com/watch?v=JYPyy-hvjYc', 1065)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (1364, N'http://csharp-video-tutorials.blogspot.com/2017/12/angular-project-setup.html', 1066)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (1365, N'http://csharp-video-tutorials.blogspot.com/2017/12/angular-project-setup-slides.html', 1066)
                INSERT INTO [dbo].[CourseDetailsBodies] ([Id], [Body], [CourseDetailsHeaderId]) VALUES (1366, N'https://www.youtube.com/watch?v=JYPyy-hvjYc', 1066)
                SET IDENTITY_INSERT [dbo].[CourseDetailsBodies] OFF
            ");

            Sql(@"
                SET IDENTITY_INSERT [dbo].[Feedbacks] ON
                INSERT INTO [dbo].[Feedbacks] ([Id], [Technology], [TrainerName], [TrainerEmail], [Punctuality], [TechnologyStrength], [Comment]) VALUES (1, N'Oracle Developer', N'Samir', NULL, N'Always In Time', N'Good', N'Every institute says they provide placements and never do that after training, but Pragim Technologies is the only institute who helped me get a job immediately after my training. The quality of the training is really good in Pragim Technologies. Real time project along with the interview questions is also explained by our OBIEE trainer.')
                INSERT INTO [dbo].[Feedbacks] ([Id], [Technology], [TrainerName], [TrainerEmail], [Punctuality], [TechnologyStrength], [Comment]) VALUES (2, N'SharePoint Developer', N'Noha', NULL, N'Always In Time', N'Good', N'Hello Pragim Technologies. I have been following your videos since last one year and just got a job in an MNC. They asked me all about SQL, GAC and DLL Hell. I have given almost 100% answer to all question just because of your video tutorials sir. I am coming from medium class family and you changed my life. I do not have enough words. God bless you sir. I promise I will do any thing for you. Hatts off to you sir. Thank you so much. You Changed my life until i live i can not forget you.')
                INSERT INTO [dbo].[Feedbacks] ([Id], [Technology], [TrainerName], [TrainerEmail], [Punctuality], [TechnologyStrength], [Comment]) VALUES (3, N'Database Administrator', N'Mona', NULL, N'Always In Time', N'Good', N'Hello KudVenkat sir, I would like to express my gratitude to You. Your DVDs with all the slides and videos helped a lot. I got a job in 2 months. I really admire the way you professionally provide information. I do not have many words to describe my admiration for You. But can only say one thing: I searched the entire internet and youtube all and I can assure You channel is the best channel that only can be found (even paid resources on the Internet can not be compared with your product). I am very grateful to you for the work you have done. if you need any help, I will be very grateful. I have shared your youtube and blog links in internet forums and social networks like facebook')
                INSERT INTO [dbo].[Feedbacks] ([Id], [Technology], [TrainerName], [TrainerEmail], [Punctuality], [TechnologyStrength], [Comment]) VALUES (4, N'Php Developer', N'Asmaa', NULL, N'Always In Time', N'Good', N'Hi Pragim Technologies, your training is so awesome. Without even ever doing c or c++ or any other programming language, I am able to develop small projects using Visual studio and even MVC. Many people suggested that it is not possible being from biochemistry background to become a .NET developer but I am sure that nothing is impossible and I proved that with your training. Your training institute is awesome and your training is more than sufficient if anyone has good motivation to become a software engineer. Its that good.')
                INSERT INTO [dbo].[Feedbacks] ([Id], [Technology], [TrainerName], [TrainerEmail], [Punctuality], [TechnologyStrength], [Comment]) VALUES (5, N'DotNet Developer', N'Ibrahim', NULL, N'Always In Time', N'Good', N'In PRAGIM Technologies, they did not ask me for any registration fee. They gave me a chance to attend the classes free for one week. After one week, if I feel the training is good I can continue, otherwise we can quit without paying anything. Dotnet trainer in PRAGIM Technologies has 8 years of experience. I also spoke to the previous batch students who were placed in different organizations. After speaking with old batch students, I became very confident obout their quality of training, trainer and placement programs.')
                INSERT INTO [dbo].[Feedbacks] ([Id], [Technology], [TrainerName], [TrainerEmail], [Punctuality], [TechnologyStrength], [Comment]) VALUES (6, N'DotNet Developer', N'Ali', NULL, N'Always In Time', N'Good', N'I got my first job as junior software developer and really want to thank you as when I was preparing for interviews videos uploaded by you on .net technologies helped so much. I bought your DVDs from your website and are very useful. Thank you Venkat sir.')
                SET IDENTITY_INSERT [dbo].[Feedbacks] OFF
            ");

            Sql(@"
                SET IDENTITY_INSERT [dbo].[Reviews] ON
                INSERT INTO [dbo].[Reviews] ([Id], [Name], [Email], [Title], [Rating], [Content], [AddReviewDate], [CourseId]) VALUES (7, N'ibrahim', N'ibrahimelbatal2@gmail.com', N'Good', 3, N'Very Good', N'2020-03-24 19:57:35', 49)
                INSERT INTO [dbo].[Reviews] ([Id], [Name], [Email], [Title], [Rating], [Content], [AddReviewDate], [CourseId]) VALUES (8, N'Ali', N'ali@gmail.com', N'Good', 3, N'Very Good', N'2020-02-24 20:07:43', 49)
                INSERT INTO [dbo].[Reviews] ([Id], [Name], [Email], [Title], [Rating], [Content], [AddReviewDate], [CourseId]) VALUES (9, N'Apples', N'ali@gmail.com', N'ajhaj', 1, N'snkskskjsk', N'2020-03-16 20:56:46', 49)
                INSERT INTO [dbo].[Reviews] ([Id], [Name], [Email], [Title], [Rating], [Content], [AddReviewDate], [CourseId]) VALUES (10, N'ibrahim', N'ibrahimelbatal2@gmail.com', N'Good', 4, N'Very Good', N'2020-03-28 17:50:01', 11)
                SET IDENTITY_INSERT [dbo].[Reviews] OFF
               ");

            Sql(@"
                INSERT INTO [dbo].[AspNetUsers] ([Id], [Email], [EmailConfirmed], [PasswordHash], [SecurityStamp], [PhoneNumber], [PhoneNumberConfirmed], [TwoFactorEnabled], [LockoutEndDateUtc], [LockoutEnabled], [AccessFailedCount], [UserName], [FirstName], [LastName]) VALUES (N'3bb4729f-2c52-468e-8bbb-9a9eae080abf', N'ibrahimelbatal2@gmail.com', 0, N'AM3WbSj2tEr7yEaQOY5tMIbnghTA1tPM4SCkBnKPrSehPzTGnt7xVhYQGReHUsX5bQ==', N'2a911582-2586-4df7-aef6-1e86993611b0', NULL, 0, 0, NULL, 1, 0, N'Ibrahim Elbatal', N'Ibrahim', N'Elbatal')
            ");

            Sql(@"
                SET IDENTITY_INSERT [dbo].[BillingInfos] ON
                INSERT INTO [dbo].[BillingInfos] ([Id], [Company], [ZipCode], [Address1], [Address2], [City], [Country], [UserId]) VALUES (13, N'company', N'12345', N'line1', N'line2', N'city', N'country', N'3bb4729f-2c52-468e-8bbb-9a9eae080abf')
                SET IDENTITY_INSERT [dbo].[BillingInfos] OFF
            ");

            Sql(@"
                SET IDENTITY_INSERT [dbo].[ShippingInfos] ON
                INSERT INTO [dbo].[ShippingInfos] ([Id], [Company], [ZipCode], [Address1], [Address2], [City], [Country], [UserId]) VALUES (13, N'company', N'12345', N'line1', N'line2', N'city', N'country', N'3bb4729f-2c52-468e-8bbb-9a9eae080abf')
                SET IDENTITY_INSERT [dbo].[ShippingInfos] OFF
                ");
        }

        public override void Down()
        {
        }
    }
}
