// <auto-generated />
namespace PragimCourses.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updateZipCodeType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateZipCodeType));
        
        string IMigrationMetadata.Id
        {
            get { return "202004041440177_updateZipCodeType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
